# Generated by Django 2.1.2 on 2018-10-26 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Infos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=250, unique=True)),
                ('time', models.CharField(max_length=300)),
                ('link', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'infos',
                'managed': True,
            },
        ),
    ]
