# Generated by Django 2.1.1 on 2018-10-12 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('City', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anqing',
            options={},
        ),
        migrations.AlterModelOptions(
            name='hefei',
            options={},
        ),
    ]
