# Generated by Django 2.1.1 on 2018-10-12 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('City', '0002_auto_20181012_1652'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anqing',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='hefei',
            options={'managed': False},
        ),
    ]
